"""empty message

Revision ID: 808fb1b857c5
Revises: 47c3fbf3ef76
Create Date: 2025-04-13 11:40:18.770155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '808fb1b857c5'
down_revision: Union[str, None] = '47c3fbf3ef76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('sellers_id', sa.Integer(), nullable=False))
    op.add_column('feedback', sa.Column('buyers_id', sa.Integer(), nullable=False))
    op.drop_constraint('feedback_buyer_id_fkey', 'feedback', type_='foreignkey')
    op.drop_constraint('feedback_seller_id_fkey', 'feedback', type_='foreignkey')
    op.create_foreign_key(None, 'feedback', 'users', ['buyers_id'], ['id'])
    op.create_foreign_key(None, 'feedback', 'users', ['sellers_id'], ['id'])
    op.drop_column('feedback', 'buyer_id')
    op.drop_column('feedback', 'seller_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('feedback', sa.Column('buyer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.create_foreign_key('feedback_seller_id_fkey', 'feedback', 'users', ['seller_id'], ['id'])
    op.create_foreign_key('feedback_buyer_id_fkey', 'feedback', 'users', ['buyer_id'], ['id'])
    op.drop_column('feedback', 'buyers_id')
    op.drop_column('feedback', 'sellers_id')
    # ### end Alembic commands ###
